@host=https://localhost:7038
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI5YTFmMmIwMi03M2JjLTQxMGEtOGM2ZS0wYWUwYWYwZTY5ODEiLCJnaXZlbl9uYW1lIjoiTWF4IiwibmFtZSI6IkFkbWluIiwiZmFtaWx5X25hbWUiOiJNdXN0ZXJtYW5uIiwianRpIjoiOWQ0N2E2M2ItNTViNC00YzdiLTg1MDYtYjRkNWM3NmNmNzc5IiwidHlwIjoiQWRtaW4iLCJzdWIiOiI5YTFmMmIwMi03M2JjLTQxMGEtOGM2ZS0wYWUwYWYwZTY5ODEiLCJleHAiOjE2ODkxMDcwNjAsImlzcyI6IlNlY3VyaXR5Q29ubmVjdCIsImF1ZCI6IlNlY3VyaXR5Q29ubmVjdCJ9.gMT0eMj7kfoZP4fADd5I8pDQhQ5C15Gkb_9n_UBg02Y

GET {{host}}/admin/listemployees
Authorization: Bearer {{token}}
Content-Type: application/json


