@host=https://localhost:7038


POST {{host}}/auth/register
Content-Type: application/json

{
    "userName": "userName",
    "password": "password",

    "firstName": "Max",
    "lastName": "Musterman"

}
